### ISSUE TITLE
Developer Intro To App

### ISSUE THREAD

**Issue by dhruv2601** [dhruv2601/News-Ton#17]

**Comment by luizbaldi** [comment]
Hi! I want to help you with this issue and it's my first time contributing to open source projects. Can you explain better whats the situation?

**Comment by prudx** [comment]
How's it going, also interested in creating apps, made my first android one today, would be happy to collaborate :)

**Comment by anubhakushwaha** [comment]
@dhruv2601 can I work upon this? I will provide a sample by tomorrow.

**Comment by dhruv2601** [comment]
@anubhakushwaha you are most welcome to do that. Would be great to see your sample.

**Comment by anubhakushwaha** [comment]
@dhruv2601 Is this appropriate? 
https://github.com/IntruderShanky/FunkyHeader
Else let me know I will search for something else.

**Comment by salRoid** [comment]
if you want a developer intro like in my app Filmy , I can make similar to that one or a better one that one.
